### ISSUE TITLE
Make code and output better distinguishable in PDF via LaTeX

### ISSUE THREAD

**Issue by mmcky** [executablebooks/sphinx-jupyterbook-latex#10]
**Is your feature request related to a problem? Please describe.**

It would be great to add `In` and `Out` (or colouring) to indicate output blocks to keep them visually separate from the `in` jupyter executable blocks. An example of consecutive blocks that are hard to read

<img width="675" alt="Screen Shot 2020-12-10 at 9 01 05 pm" src="https://user-images.githubusercontent.com/8263752/101757324-22e50900-3b2b-11eb-974b-4b4090a89c09.png">

**Describe the solution you'd like**

This [document](https://python.quantecon.org/_downloads/pdf/linear_algebra.pdf) has one solution that we have used at `quantecon` in the past. 

Another would be to just make the output block a different line colour

**Comment by mmcky** [comment]
This is the tracking issue for [this feature request](https://github.com/executablebooks/jupyter-book/issues/1234) but there are some excellent comments / ideas on how to best implement the `output` wrappers which may help with distinguishing the output blocks from the code blocks.

**Comment by mmcky** [comment]
Here are some good ideas on reclassifying output from @pradyunsg 

```
Instead of using sphinxVerbatim for code cells and their output use:

sphinxVerbatimCode
sphinxVerbatimOutput
sphinxVerbatimException
This would allow to use different visual representation for these.
The default could be to use the same visual representation for all three environments to preserve the current behavior.
But the environments could be modified via Sphinx LaTeX settings.
```

**Comment by pradyunsg** [comment]
I'm pretty sure that it wasn't me.

**Comment by mmcky** [comment]
> I'm pretty sure that it wasn't me.

Sorry -- dang autofill. Corrected :-)

**Comment by AakashGfude** [comment]
We ended up creating wrapper nodes around code cells, to achieve this instead of modifying the literal_blocks in sphinx, as it is less invasive. 

https://github.com/executablebooks/sphinx-jupyterbook-latex/pull/87
