### ISSUE TITLE
Should myst_nb be optional dependency?

### ISSUE THREAD

**Issue by AakashGfude** [executablebooks/sphinx-jupyterbook-latex#110]
### Describe the bug

Since we have to check myst_nb version to see what nodes the transforms should generate. https://github.com/executablebooks/sphinx-jupyterbook-latex/blob/master/sphinx_jupyterbook_latex/transforms.py#L44 . 
Should it be kept as an optional dependency, in extra_requires : https://github.com/executablebooks/sphinx-jupyterbook-latex/blob/master/setup.cfg#L34 . I think it should be moved to https://github.com/executablebooks/sphinx-jupyterbook-latex/blob/master/setup.cfg#L24 

### Reproduce the bug

1. pip install sphinx-jupyterbook-latex.
2. does not install/re-install the appropriate version of myst-nb wanted by this package. Instead uses whatever was in the system.

**Comment by mmcky** [comment]
I agree @AakashGfude I think `myst-nb` should be moved to `install_requires`.

**Comment by mmcky** [comment]
> I agree @AakashGfude I think `myst-nb` should be moved to `install_requires`.

So with @chrisjsewell reminder that circular dependencies where an issue I think its great you've worked on #112
