### ISSUE TITLE
Equation Numbering with Chapter Referencing

### ISSUE THREAD

**Issue by mmcky** [executablebooks/sphinx-jupyterbook-latex#48]
**Is your feature request related to a problem? Please describe.**

@jstac has requested

```
it would be ideal to have unique equation numbers of the form (3.4) for eq 4 in Ch 3,
rather than restarting the numbering in each section
```

**Describe the solution you'd like**

Is this behaviour implemented if we ensure `sphinx-multitoc-numbering` is used?

**Comment by mmcky** [comment]
@AakashGfude this looks useful for updating the default preamble using `asmath` package

https://tex.stackexchange.com/questions/106935/how-to-include-chapter-number-in-equation-numbers

**Comment by AakashGfude** [comment]
@mmcky apparently these solutions don't work when `"latex_toplevel_sectioning" = "part"`, the extension does this numbering by default when `"latex_toplevel_sectioning" = "section"` . Will find a part specific solution.
